<?php

namespace Louvre\TicketBundle\Repository;

/**
 * TicketsOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketsOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
